### ISSUE TITLE
The circuit breaker module uses Promise.defer...

### ISSUE THREAD

**Issue by Hummel-Mors** [pablolb/promise-circuitbreaker#6]
I get the following error message in the console:

(Node: 4888) Warning: Promise.defer is deprecated and will be removed in a future version. Use new promise instead...

Question: Is it possible to use the native promise method, and throw it out the bluebird extension?

**Comment by rakeshongithub** [comment]
I am also getting same warning. Please update the package with native promise method.

**Comment by pablolb** [comment]
Hi, thanks for pointing this out, I hadn't seen the warning.  Sorry for the delay, I am taking some time off.

Please update to the latest version and the issue should be fixed.

You can also use the native Promise implementation by configuration (`{Promise: Promise}` as options in the constructor) - the tests and example app work, but I haven't tried it in a production environment.
